"""initial

Revision ID: 9e9aab8a1789
Revises: 
Create Date: 2023-03-21 16:59:48.247513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e9aab8a1789"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column("cost", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_statistics_date"), "statistics", ["date"], unique=True)
    op.create_index(
        op.f("ix_statistics_is_active"), "statistics", ["is_active"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_statistics_is_active"), table_name="statistics")
    op.drop_index(op.f("ix_statistics_date"), table_name="statistics")
    op.drop_table("statistics")
    # ### end Alembic commands ###
